// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/certifier.proto

package ccaspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CertifierService_SubmitCommit_FullMethodName    = "/ccas.CertifierService/SubmitCommit"
	CertifierService_SyncFromStorage_FullMethodName = "/ccas.CertifierService/SyncFromStorage"
)

// CertifierServiceClient is the client API for CertifierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CertifierServiceClient interface {
	SubmitCommit(ctx context.Context, in *SubmitCommitRequest, opts ...grpc.CallOption) (*SubmitCommitResponse, error)
	SyncFromStorage(ctx context.Context, in *SyncFromStorageRequest, opts ...grpc.CallOption) (*SyncFromStorageResponse, error)
}

type certifierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCertifierServiceClient(cc grpc.ClientConnInterface) CertifierServiceClient {
	return &certifierServiceClient{cc}
}

func (c *certifierServiceClient) SubmitCommit(ctx context.Context, in *SubmitCommitRequest, opts ...grpc.CallOption) (*SubmitCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitCommitResponse)
	err := c.cc.Invoke(ctx, CertifierService_SubmitCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certifierServiceClient) SyncFromStorage(ctx context.Context, in *SyncFromStorageRequest, opts ...grpc.CallOption) (*SyncFromStorageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncFromStorageResponse)
	err := c.cc.Invoke(ctx, CertifierService_SyncFromStorage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertifierServiceServer is the server API for CertifierService service.
// All implementations must embed UnimplementedCertifierServiceServer
// for forward compatibility.
type CertifierServiceServer interface {
	SubmitCommit(context.Context, *SubmitCommitRequest) (*SubmitCommitResponse, error)
	SyncFromStorage(context.Context, *SyncFromStorageRequest) (*SyncFromStorageResponse, error)
	mustEmbedUnimplementedCertifierServiceServer()
}

// UnimplementedCertifierServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCertifierServiceServer struct{}

func (UnimplementedCertifierServiceServer) SubmitCommit(context.Context, *SubmitCommitRequest) (*SubmitCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitCommit not implemented")
}
func (UnimplementedCertifierServiceServer) SyncFromStorage(context.Context, *SyncFromStorageRequest) (*SyncFromStorageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncFromStorage not implemented")
}
func (UnimplementedCertifierServiceServer) mustEmbedUnimplementedCertifierServiceServer() {}
func (UnimplementedCertifierServiceServer) testEmbeddedByValue()                          {}

// UnsafeCertifierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CertifierServiceServer will
// result in compilation errors.
type UnsafeCertifierServiceServer interface {
	mustEmbedUnimplementedCertifierServiceServer()
}

func RegisterCertifierServiceServer(s grpc.ServiceRegistrar, srv CertifierServiceServer) {
	// If the following call panics, it indicates UnimplementedCertifierServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CertifierService_ServiceDesc, srv)
}

func _CertifierService_SubmitCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertifierServiceServer).SubmitCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertifierService_SubmitCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertifierServiceServer).SubmitCommit(ctx, req.(*SubmitCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertifierService_SyncFromStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncFromStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertifierServiceServer).SyncFromStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertifierService_SyncFromStorage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertifierServiceServer).SyncFromStorage(ctx, req.(*SyncFromStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CertifierService_ServiceDesc is the grpc.ServiceDesc for CertifierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CertifierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ccas.CertifierService",
	HandlerType: (*CertifierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitCommit",
			Handler:    _CertifierService_SubmitCommit_Handler,
		},
		{
			MethodName: "SyncFromStorage",
			Handler:    _CertifierService_SyncFromStorage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/certifier.proto",
}
