// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/certifier.proto

package ccaspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncFromStorageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFromStorageRequest) Reset() {
	*x = SyncFromStorageRequest{}
	mi := &file_proto_certifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFromStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFromStorageRequest) ProtoMessage() {}

func (x *SyncFromStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFromStorageRequest.ProtoReflect.Descriptor instead.
func (*SyncFromStorageRequest) Descriptor() ([]byte, []int) {
	return file_proto_certifier_proto_rawDescGZIP(), []int{0}
}

type SyncFromStorageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFromStorageResponse) Reset() {
	*x = SyncFromStorageResponse{}
	mi := &file_proto_certifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFromStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFromStorageResponse) ProtoMessage() {}

func (x *SyncFromStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFromStorageResponse.ProtoReflect.Descriptor instead.
func (*SyncFromStorageResponse) Descriptor() ([]byte, []int) {
	return file_proto_certifier_proto_rawDescGZIP(), []int{1}
}

type ReadEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	VersionSeen   uint64                 `protobuf:"varint,2,opt,name=version_seen,json=versionSeen,proto3" json:"version_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadEntry) Reset() {
	*x = ReadEntry{}
	mi := &file_proto_certifier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEntry) ProtoMessage() {}

func (x *ReadEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certifier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEntry.ProtoReflect.Descriptor instead.
func (*ReadEntry) Descriptor() ([]byte, []int) {
	return file_proto_certifier_proto_rawDescGZIP(), []int{2}
}

func (x *ReadEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReadEntry) GetVersionSeen() uint64 {
	if x != nil {
		return x.VersionSeen
	}
	return 0
}

type WriteEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteEntry) Reset() {
	*x = WriteEntry{}
	mi := &file_proto_certifier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteEntry) ProtoMessage() {}

func (x *WriteEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certifier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteEntry.ProtoReflect.Descriptor instead.
func (*WriteEntry) Descriptor() ([]byte, []int) {
	return file_proto_certifier_proto_rawDescGZIP(), []int{3}
}

func (x *WriteEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SubmitCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	ReadSet       []*ReadEntry           `protobuf:"bytes,2,rep,name=read_set,json=readSet,proto3" json:"read_set,omitempty"`
	WriteSet      []*WriteEntry          `protobuf:"bytes,3,rep,name=write_set,json=writeSet,proto3" json:"write_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitCommitRequest) Reset() {
	*x = SubmitCommitRequest{}
	mi := &file_proto_certifier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCommitRequest) ProtoMessage() {}

func (x *SubmitCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certifier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCommitRequest.ProtoReflect.Descriptor instead.
func (*SubmitCommitRequest) Descriptor() ([]byte, []int) {
	return file_proto_certifier_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitCommitRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *SubmitCommitRequest) GetReadSet() []*ReadEntry {
	if x != nil {
		return x.ReadSet
	}
	return nil
}

func (x *SubmitCommitRequest) GetWriteSet() []*WriteEntry {
	if x != nil {
		return x.WriteSet
	}
	return nil
}

type SubmitCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Committed     bool                   `protobuf:"varint,2,opt,name=committed,proto3" json:"committed,omitempty"`
	CommitSeq     uint64                 `protobuf:"varint,3,opt,name=commit_seq,json=commitSeq,proto3" json:"commit_seq,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitCommitResponse) Reset() {
	*x = SubmitCommitResponse{}
	mi := &file_proto_certifier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCommitResponse) ProtoMessage() {}

func (x *SubmitCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certifier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCommitResponse.ProtoReflect.Descriptor instead.
func (*SubmitCommitResponse) Descriptor() ([]byte, []int) {
	return file_proto_certifier_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitCommitResponse) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *SubmitCommitResponse) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

func (x *SubmitCommitResponse) GetCommitSeq() uint64 {
	if x != nil {
		return x.CommitSeq
	}
	return 0
}

func (x *SubmitCommitResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_certifier_proto protoreflect.FileDescriptor

const file_proto_certifier_proto_rawDesc = "" +
	"\n" +
	"\x15proto/certifier.proto\x12\x04ccas\"\x18\n" +
	"\x16SyncFromStorageRequest\"\x19\n" +
	"\x17SyncFromStorageResponse\"@\n" +
	"\tReadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\fversion_seen\x18\x02 \x01(\x04R\vversionSeen\"4\n" +
	"\n" +
	"WriteEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x87\x01\n" +
	"\x13SubmitCommitRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12*\n" +
	"\bread_set\x18\x02 \x03(\v2\x0f.ccas.ReadEntryR\areadSet\x12-\n" +
	"\twrite_set\x18\x03 \x03(\v2\x10.ccas.WriteEntryR\bwriteSet\"\x82\x01\n" +
	"\x14SubmitCommitResponse\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12\x1c\n" +
	"\tcommitted\x18\x02 \x01(\bR\tcommitted\x12\x1d\n" +
	"\n" +
	"commit_seq\x18\x03 \x01(\x04R\tcommitSeq\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason2\xa9\x01\n" +
	"\x10CertifierService\x12E\n" +
	"\fSubmitCommit\x12\x19.ccas.SubmitCommitRequest\x1a\x1a.ccas.SubmitCommitResponse\x12N\n" +
	"\x0fSyncFromStorage\x12\x1c.ccas.SyncFromStorageRequest\x1a\x1d.ccas.SyncFromStorageResponseB(Z&github.com/vichcraft/ccas/proto/ccaspbb\x06proto3"

var (
	file_proto_certifier_proto_rawDescOnce sync.Once
	file_proto_certifier_proto_rawDescData []byte
)

func file_proto_certifier_proto_rawDescGZIP() []byte {
	file_proto_certifier_proto_rawDescOnce.Do(func() {
		file_proto_certifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_certifier_proto_rawDesc), len(file_proto_certifier_proto_rawDesc)))
	})
	return file_proto_certifier_proto_rawDescData
}

var file_proto_certifier_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_certifier_proto_goTypes = []any{
	(*SyncFromStorageRequest)(nil),  // 0: ccas.SyncFromStorageRequest
	(*SyncFromStorageResponse)(nil), // 1: ccas.SyncFromStorageResponse
	(*ReadEntry)(nil),               // 2: ccas.ReadEntry
	(*WriteEntry)(nil),              // 3: ccas.WriteEntry
	(*SubmitCommitRequest)(nil),     // 4: ccas.SubmitCommitRequest
	(*SubmitCommitResponse)(nil),    // 5: ccas.SubmitCommitResponse
}
var file_proto_certifier_proto_depIdxs = []int32{
	2, // 0: ccas.SubmitCommitRequest.read_set:type_name -> ccas.ReadEntry
	3, // 1: ccas.SubmitCommitRequest.write_set:type_name -> ccas.WriteEntry
	4, // 2: ccas.CertifierService.SubmitCommit:input_type -> ccas.SubmitCommitRequest
	0, // 3: ccas.CertifierService.SyncFromStorage:input_type -> ccas.SyncFromStorageRequest
	5, // 4: ccas.CertifierService.SubmitCommit:output_type -> ccas.SubmitCommitResponse
	1, // 5: ccas.CertifierService.SyncFromStorage:output_type -> ccas.SyncFromStorageResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_certifier_proto_init() }
func file_proto_certifier_proto_init() {
	if File_proto_certifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_certifier_proto_rawDesc), len(file_proto_certifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_certifier_proto_goTypes,
		DependencyIndexes: file_proto_certifier_proto_depIdxs,
		MessageInfos:      file_proto_certifier_proto_msgTypes,
	}.Build()
	File_proto_certifier_proto = out.File
	file_proto_certifier_proto_goTypes = nil
	file_proto_certifier_proto_depIdxs = nil
}
