// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/storage.proto

package ccaspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type CommitWrite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	NewVersion    uint64                 `protobuf:"varint,3,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitWrite) Reset() {
	*x = CommitWrite{}
	mi := &file_proto_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitWrite) ProtoMessage() {}

func (x *CommitWrite) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitWrite.ProtoReflect.Descriptor instead.
func (*CommitWrite) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{2}
}

func (x *CommitWrite) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CommitWrite) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CommitWrite) GetNewVersion() uint64 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

type ApplyCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitSeq     uint64                 `protobuf:"varint,1,opt,name=commit_seq,json=commitSeq,proto3" json:"commit_seq,omitempty"`
	TxnId         string                 `protobuf:"bytes,2,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Writes        []*CommitWrite         `protobuf:"bytes,3,rep,name=writes,proto3" json:"writes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyCommitRequest) Reset() {
	*x = ApplyCommitRequest{}
	mi := &file_proto_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyCommitRequest) ProtoMessage() {}

func (x *ApplyCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyCommitRequest.ProtoReflect.Descriptor instead.
func (*ApplyCommitRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyCommitRequest) GetCommitSeq() uint64 {
	if x != nil {
		return x.CommitSeq
	}
	return 0
}

func (x *ApplyCommitRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *ApplyCommitRequest) GetWrites() []*CommitWrite {
	if x != nil {
		return x.Writes
	}
	return nil
}

type ApplyCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyCommitResponse) Reset() {
	*x = ApplyCommitResponse{}
	mi := &file_proto_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyCommitResponse) ProtoMessage() {}

func (x *ApplyCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyCommitResponse.ProtoReflect.Descriptor instead.
func (*ApplyCommitResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{4}
}

func (x *ApplyCommitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LoadInitialDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]string      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadInitialDataRequest) Reset() {
	*x = LoadInitialDataRequest{}
	mi := &file_proto_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadInitialDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadInitialDataRequest) ProtoMessage() {}

func (x *LoadInitialDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadInitialDataRequest.ProtoReflect.Descriptor instead.
func (*LoadInitialDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{5}
}

func (x *LoadInitialDataRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoadInitialDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadInitialDataResponse) Reset() {
	*x = LoadInitialDataResponse{}
	mi := &file_proto_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadInitialDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadInitialDataResponse) ProtoMessage() {}

func (x *LoadInitialDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadInitialDataResponse.ProtoReflect.Descriptor instead.
func (*LoadInitialDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{6}
}

type DumpStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpStateRequest) Reset() {
	*x = DumpStateRequest{}
	mi := &file_proto_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpStateRequest) ProtoMessage() {}

func (x *DumpStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpStateRequest.ProtoReflect.Descriptor instead.
func (*DumpStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{7}
}

type DumpStateEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpStateEntry) Reset() {
	*x = DumpStateEntry{}
	mi := &file_proto_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpStateEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpStateEntry) ProtoMessage() {}

func (x *DumpStateEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpStateEntry.ProtoReflect.Descriptor instead.
func (*DumpStateEntry) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{8}
}

func (x *DumpStateEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DumpStateEntry) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DumpStateResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Entries       map[string]*DumpStateEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpStateResponse) Reset() {
	*x = DumpStateResponse{}
	mi := &file_proto_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpStateResponse) ProtoMessage() {}

func (x *DumpStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpStateResponse.ProtoReflect.Descriptor instead.
func (*DumpStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{9}
}

func (x *DumpStateResponse) GetEntries() map[string]*DumpStateEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_proto_storage_proto protoreflect.FileDescriptor

const file_proto_storage_proto_rawDesc = "" +
	"\n" +
	"\x13proto/storage.proto\x12\x04ccas\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"S\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"V\n" +
	"\vCommitWrite\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1f\n" +
	"\vnew_version\x18\x03 \x01(\x04R\n" +
	"newVersion\"u\n" +
	"\x12ApplyCommitRequest\x12\x1d\n" +
	"\n" +
	"commit_seq\x18\x01 \x01(\x04R\tcommitSeq\x12\x15\n" +
	"\x06txn_id\x18\x02 \x01(\tR\x05txnId\x12)\n" +
	"\x06writes\x18\x03 \x03(\v2\x11.ccas.CommitWriteR\x06writes\"+\n" +
	"\x13ApplyCommitResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x8d\x01\n" +
	"\x16LoadInitialDataRequest\x12:\n" +
	"\x04data\x18\x01 \x03(\v2&.ccas.LoadInitialDataRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x19\n" +
	"\x17LoadInitialDataResponse\"\x12\n" +
	"\x10DumpStateRequest\"@\n" +
	"\x0eDumpStateEntry\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\"\xa5\x01\n" +
	"\x11DumpStateResponse\x12>\n" +
	"\aentries\x18\x01 \x03(\v2$.ccas.DumpStateResponse.EntriesEntryR\aentries\x1aP\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.ccas.DumpStateEntryR\x05value:\x028\x012\x8e\x02\n" +
	"\x0eStorageService\x12*\n" +
	"\x03Get\x12\x10.ccas.GetRequest\x1a\x11.ccas.GetResponse\x12B\n" +
	"\vApplyCommit\x12\x18.ccas.ApplyCommitRequest\x1a\x19.ccas.ApplyCommitResponse\x12N\n" +
	"\x0fLoadInitialData\x12\x1c.ccas.LoadInitialDataRequest\x1a\x1d.ccas.LoadInitialDataResponse\x12<\n" +
	"\tDumpState\x12\x16.ccas.DumpStateRequest\x1a\x17.ccas.DumpStateResponseB(Z&github.com/vichcraft/ccas/proto/ccaspbb\x06proto3"

var (
	file_proto_storage_proto_rawDescOnce sync.Once
	file_proto_storage_proto_rawDescData []byte
)

func file_proto_storage_proto_rawDescGZIP() []byte {
	file_proto_storage_proto_rawDescOnce.Do(func() {
		file_proto_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_storage_proto_rawDesc), len(file_proto_storage_proto_rawDesc)))
	})
	return file_proto_storage_proto_rawDescData
}

var file_proto_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_storage_proto_goTypes = []any{
	(*GetRequest)(nil),              // 0: ccas.GetRequest
	(*GetResponse)(nil),             // 1: ccas.GetResponse
	(*CommitWrite)(nil),             // 2: ccas.CommitWrite
	(*ApplyCommitRequest)(nil),      // 3: ccas.ApplyCommitRequest
	(*ApplyCommitResponse)(nil),     // 4: ccas.ApplyCommitResponse
	(*LoadInitialDataRequest)(nil),  // 5: ccas.LoadInitialDataRequest
	(*LoadInitialDataResponse)(nil), // 6: ccas.LoadInitialDataResponse
	(*DumpStateRequest)(nil),        // 7: ccas.DumpStateRequest
	(*DumpStateEntry)(nil),          // 8: ccas.DumpStateEntry
	(*DumpStateResponse)(nil),       // 9: ccas.DumpStateResponse
	nil,                             // 10: ccas.LoadInitialDataRequest.DataEntry
	nil,                             // 11: ccas.DumpStateResponse.EntriesEntry
}
var file_proto_storage_proto_depIdxs = []int32{
	2,  // 0: ccas.ApplyCommitRequest.writes:type_name -> ccas.CommitWrite
	10, // 1: ccas.LoadInitialDataRequest.data:type_name -> ccas.LoadInitialDataRequest.DataEntry
	11, // 2: ccas.DumpStateResponse.entries:type_name -> ccas.DumpStateResponse.EntriesEntry
	8,  // 3: ccas.DumpStateResponse.EntriesEntry.value:type_name -> ccas.DumpStateEntry
	0,  // 4: ccas.StorageService.Get:input_type -> ccas.GetRequest
	3,  // 5: ccas.StorageService.ApplyCommit:input_type -> ccas.ApplyCommitRequest
	5,  // 6: ccas.StorageService.LoadInitialData:input_type -> ccas.LoadInitialDataRequest
	7,  // 7: ccas.StorageService.DumpState:input_type -> ccas.DumpStateRequest
	1,  // 8: ccas.StorageService.Get:output_type -> ccas.GetResponse
	4,  // 9: ccas.StorageService.ApplyCommit:output_type -> ccas.ApplyCommitResponse
	6,  // 10: ccas.StorageService.LoadInitialData:output_type -> ccas.LoadInitialDataResponse
	9,  // 11: ccas.StorageService.DumpState:output_type -> ccas.DumpStateResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_storage_proto_init() }
func file_proto_storage_proto_init() {
	if File_proto_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_storage_proto_rawDesc), len(file_proto_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_storage_proto_goTypes,
		DependencyIndexes: file_proto_storage_proto_depIdxs,
		MessageInfos:      file_proto_storage_proto_msgTypes,
	}.Build()
	File_proto_storage_proto = out.File
	file_proto_storage_proto_goTypes = nil
	file_proto_storage_proto_depIdxs = nil
}
